#pragma once

#define MBEDTLS_AES_C
#define MBEDTLS_BLOCK_CIPHER_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_ENTROPY_FORCE_SHA256
#define MBEDTLS_GCM_C
#define MBEDTLS_MD_C
#define MBEDTLS_SHA256_C

#define MBEDTLS_NO_UDBL_DIVISION
